# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Calculator Scenario 22"

on:
  push:
    branches: [ "main" ]
    paths: [ 'samples/Calculator/tests/**', 'samples/Calculator/src/**', '.github/workflows/Calculator_Scenario22.yml', 'samples/Calculator/scenarios/scenario22/coverage.runsettings' ]

env:
  STATIC_INSTRUMENTATION_DIR: "${{ github.workspace }}/samples/Calculator/src/Calculator.Console"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./samples/Calculator/tests/Calculator.Console.Tests
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore dependencies (Console project)
      run: dotnet restore ../../src/Calculator.Console/Calculator.Console.csproj
    - name: Build
      run: dotnet build --no-restore
    - name: Build  (Console project)
      run: dotnet build --no-restore ../../src/Calculator.Console/Calculator.Console.csproj
    - name: Test
      run: dotnet test --settings ../../scenarios/scenario22/coverage.runsettings --no-build --verbosity normal
    - name: Install dotnet-coverage
      run: dotnet tool install -g dotnet-coverage
    - name: Convert .coverage report to cobertura
      run: dotnet-coverage merge $GITHUB_WORKSPACE/samples/Calculator/tests/Calculator.Console.Tests/TestResults/**/*.coverage -f cobertura -o $GITHUB_WORKSPACE/report.cobertura.xml
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: '${{ github.workspace }}/report.cobertura.xml'
        targetdir: '${{ github.workspace }}/coveragereport'
        reporttypes: 'MarkdownSummaryGithub'
    - name: Upload coverage into summary
      run: cat $GITHUB_WORKSPACE/coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./**/TestResults/**/*.coverage
